### PR TITLE
Indel feature add

### PR DESCRIPTION
**Pull request by willhooper**
The iRosetta_Lookup.exe binaries need to be recompiled for these changes to work - you can find the  source at github.com/willhooper/LoopHash

- Added controls to indel.py for symmetry
- Modified indel.py and daemon.py to reflect new iRosetta_Lookup.exe input format
- Bugfixes (probably introduced new ones as well)

Have a good weekend! 

Will

### CODE REVIEW

**Comment by walcob** [comment]
I added LoopHash as a submodule for InteractiveROSETTA so it will be easier to update that part.

**Comment by walcob** [comment]
iRosetta_Lookup_osx.exe is segfaulting

**Comment by walcob** [comment]
It might be segfaulting because I have it set up wrong.  Hold on...

**Comment by walcob** [comment]
Still not working.

**Comment by willhooper** [comment]
Uh oh.. is the input file being written out right? It should be in the sandbox. You built it from the latest version on my github right?

I can help take a look tomorrow if you're gonna be around.. it's probably a quick fix.

**Pull request merged**
